### PR TITLE
Added Dark Mode

### PR DESCRIPTION
**Pull request by JadugarKalakaboola**
### Changes proposed
1. Added Dark and light theme.
2. Made a light theme class fir each css property. Dark Mode remains default and there is no change in it.

### Screenshots
Dark Theme
image
Light Theme
image
image

### Note to reviewers
Though I have edited the css with responsiveness, but please have a review.

### Check List (Check all the applicable boxes) 
- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

---

### Code of Conduct
- [x ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/Movie-land/blob/main/CODE_OF_CONDUCT.md) 🖖

---

If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
Feel free to check out other cool **open-source** repositories and communities:
[Kabir0x23](https://github.com/kabir0x23) • [Cryptoverse Web3](https://github.com/CryptoverseWeb3) • [Thecyberworld](https://github.com/thecyberworld)

### CODE REVIEW

**Review by kabir0x23 — APPROVED** [review]
Good work @JadugarKalakaboola 

Thanks for contributing to this project

**Comment by kabir0x23** [comment]
@JadugarKalakaboola 



You have to do Two things now:

  -  do not include package-lock.json file in your commits
   - and do not delete that file
   - just copy the same file from our project and paste those into your file and push the code.

then I will be able to merge this pull request.

Thanks.

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
You have to do some changes, as mentioned above

**Comment by JadugarKalakaboola** [comment]
do you mean I have to copy this file into my package-lock file?
image

**Comment by kabir0x23** [comment]
> do you mean I have to copy this file into my package-lock file? image

yes, because, we don't commit those files with the changes
because these files always got changed on local machine

so just copy our file into yours, as it is, and just push the code only
- no need to create a New Pull Request
- once you pushed the code, the code will automatically reflect.

**Comment by JadugarKalakaboola** [comment]
Ok great. Thanks

**Comment by JadugarKalakaboola** [comment]
I have fixed the package.json file. :)

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks for contributing to this project

**Pull request merged**
