### PR TITLE
New feature - Added release date below movie name in card

### PR DESCRIPTION
**Pull request by najeebkp**

### CODE REVIEW

**Review by kabir0x23 — COMMENTED** [review]
Nice, you did a great work.

that screenshot that i have mention was just an example.
image
image

you made exactly the same. that's great.

- Can you change the design of the date ?

and one thing 
- can you tell me what more things we can add, like date etx?

**Comment by najeebkp** [comment]
you mean you want something like this "date : 2016" ?

**Comment by kabir0x23** [comment]
> you mean you want something like this "date : 2016" ?

I mean design of date.
- can you create a new design of your choice
Thanks.

**Comment by najeebkp** [comment]
frankly, i'm not a good design person brother.

**Comment by kabir0x23** [comment]
Thanks for contributing to this project

**Pull request merged**
