### PR TITLE
added dark and light theme mode successfully

### PR DESCRIPTION
**Pull request by codewithnadeem14502**
### Check List (Check all the applicable boxes) 
- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

### Code of Conduct
- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/Movie-land/blob/main/CODE_OF_CONDUCT.md) 🖖

---

If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
Feel free to check out other cool **open-source** repositories and communities:
[Kabir0x23](https://github.com/kabir0x23) • [Cryptoverse Web3](https://github.com/CryptoverseWeb3) • [Thecyberworld](https://github.com/thecyberworld)

### CODE REVIEW

**Comment by codewithnadeem14502** [comment]
sir, i am here to get a new experience of open source and hacktoberfest is my first step to contribution

**Comment by kabir0x23** [comment]
> sir, i am here to get a new experience of open source and hacktoberfest is my first step to contribution

hacktober fest is starting from oct, send the new Pull request on oct 1.

and reverse the deleted package json file

**Comment by codewithnadeem14502** [comment]
how to reverse the deleted package JSON file, sir , I don't know? and my added themes working correctly sir (any feedback , i am also made it responsive )? I am new to react js . so this contribution help me a lot in understanding the concept of react js , thank you for posting this issue and I would love to contribute more under you sir @kabir0x23

**Comment by kabir0x23** [comment]
> how to reverse the deleted package JSON file, sir , I don't know? and my added themes working correctly sir (any feedback , i am also made it responsive )? I am new to react js . so this contribution help me a lot in understanding the concept of react js , thank you for posting this issue and I would love to contribute more under you sir @kabir0x23

copy the code from our json file and add it to you project and just upload there, 
we will automatically get here.

**Comment by codewithnadeem14502** [comment]
i will fix that and what about the theme switch, can you give me feedback on it

**Comment by kabir0x23** [comment]
> I will fix that ( add locked JSON or simple JSON file ? )t and what about the theme switch, can you give me feedback on it

I can't check, first, you have to upload this file  https://github.com/kabir0x23/MovieLand/blob/main/package.json same to same 

then i will able to view your content .

**Comment by codewithnadeem14502** [comment]
done sir , please check it

**Comment by kabir0x23** [comment]
you have to use this file: https://github.com/kabir0x23/MovieLand/blob/main/package-lock.json
and have to upload in the project folder, not anywhere else.

**Comment by kabir0x23** [comment]
and if you are doing this for hacktober fest then you have to do this on oct 1, otherwise it will not be count in hacktoberfest

**Comment by codewithnadeem14502** [comment]
sir :( i want this to add in hacktoberfest, i have raised because you want to see the feature (dark and light theme ) , is there any other chance to get this task in my hacktoberfest? please help me

**Comment by kabir0x23** [comment]
> sir :( i want this to add in hacktoberfest, i have raised because you want to see the feature (dark and light theme ) , is there any other chance to get this task in my hacktoberfest? please help me 
> 

Yes , it will be in hacktoberfest 

You sent the In September.
Hacktoberfest starts from today
So I will accept your pull request Today
After checking the code. 👍🏼

**Pull request merged**
