### PR TITLE
[FEATURE]:Added footer with copyright line and social icons with hover Effects[Fixes #41]

### LINKED ISSUE #41: [FEATURE] Adding Footer to the website
### Detailed description

Adding Footer to the website which include
-copyright line
-social icons with hover effect and links to them if got available.

### Context

To give more information about the owner of the website and their social media links.

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Kritika30032002**
issue #41  fixed 

 
### Check List (Check all the applicable boxes) 
- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

---

### Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/Movie-land/blob/main/CODE_OF_CONDUCT.md) 🖖

---

If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
Feel free to check out other cool **open-source** repositories and communities:
[Kabir0x23](https://github.com/kabir0x23) • [Cryptoverse Web3](https://github.com/CryptoverseWeb3) • [Thecyberworld](https://github.com/thecyberworld)

### CODE REVIEW

**Comment by Kritika30032002** [comment]
@kabir0x23

**Comment by Kritika30032002** [comment]
How long it takes for you to review any PR ?   @kabir0x23

**Comment by kabir0x23** [comment]
> How long it takes for you to review any PR ? @kabir0x23

going to merge

having many open-source projects + other things and having to manage by myslef takes lots of time. 

That's why it is taking time to merge and review.

I am on it 

Thanks for the wait.

**Comment by Kritika30032002** [comment]
> > How long it takes for you to review any PR ? @kabir0x23
> 
> going to merge
> 
> having many open-source projects + other things and having to manage by myslef takes lots of time.
> 
> That's why it is taking time to merge and review.
> 
> I am on it
> 
> Thanks for the wait.

That's okay 
I asked this because it has been 2 days I submitted my PR

**Review by kabir0x23 — APPROVED** [review]
Great 😄

Thanks for contributing to this project.

If you want to contribute more to open-source then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
