### PR TITLE
added custom scrollbar in website

### PR DESCRIPTION
**Pull request by KushalPareek**
I want to add a custom scroll bar in your website.
I had read the Code of Conduct file.
I have attached a screenshot of a custom scroll bar. 
Please review and merged.
Thanks.

kpppp

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
Hey thanks for contributing to this project.

suggestions:
- never add git add . 
- we don;t push package-lock.json file only, until and unless we have included new deps
- you can copy the content from our project file and add it into your file in the same branch and just push the code

- and can you change the color of the bar, like grey


thank you

**Comment by KushalPareek** [comment]
I will try and send the PR. Please review it. Thanks for your help and
suggestions.

**Comment by kabir0x23** [comment]
you don't have to close the pr

when you push the changes on the same branch

code will automatically reflected on the pull request

**Comment by KushalPareek** [comment]
Sorry for that. I am beginner, so I don't know about this. Thank u 🙏 for
merging my PR.

**Pull request closed without merging**
