### PR TITLE
added dark and white theme and remove the json files

### PR DESCRIPTION
**Pull request by codewithnadeem14502**
### Check List (Check all the applicable boxes) 
- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

### Code of Conduct
- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/Movie-land/blob/main/CODE_OF_CONDUCT.md) 🖖

---

If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
Feel free to check out other cool **open-source** repositories and communities:
[Kabir0x23](https://github.com/kabir0x23) • [Cryptoverse Web3](https://github.com/CryptoverseWeb3) • [Thecyberworld](https://github.com/thecyberworld)

### CODE REVIEW

**Comment by codewithnadeem14502** [comment]
hope this will work sir , thank you

**Comment by kabir0x23** [comment]
You just removed those files again.
image


let me help you,

**Comment by kabir0x23** [comment]
> You just removed those files again. image
> 
> let me help you,

you can join discord and i will help you there.

**Comment by codewithnadeem14502** [comment]
i am already in your discord server

**Comment by codewithnadeem14502** [comment]
this is my discord user name - rdx-coder#9906 please text me or call me thank you

**Comment by codewithnadeem14502** [comment]
sir , this is my phone number you can call when me your free { 9398300727 }

**Comment by codewithnadeem14502** [comment]
if i am not wrong then you only told  me to don't include this two files

**Comment by codewithnadeem14502** [comment]
if i am not wrong then you only told  me to don't include this two files

**Comment by codewithnadeem14502** [comment]
leave it sir , i am happy that my first contribution start from your project . if you have more issue / task then i am happy to work on it thank you

**Comment by kabir0x23** [comment]
> leave it sir , i am happy that my first contribution start from your project . if you have more issue / task then i am happy to work on it thank you

hello i have a solution 
just upload the code that you have shared before

then i will help you

Will take 5 minutes of work

**Comment by codewithnadeem14502** [comment]
sir , if you don't mind can you share your twitter handle or LinkedIn or discord username please , i am so confuse

**Comment by kabir0x23** [comment]
> sir , i send you LinkedIn request please when your FREE then accept it

done.

**Comment by codewithnadeem14502** [comment]
> > sir , i send you LinkedIn request please when your FREE then accept it
> 
> done.

please chek your dm sir (LinkedIn )

**Pull request closed without merging**
